name: CI Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Linting 
        run: |
          pip install flake8
          flake8 .

      - name: Run Type Checking 
        run: |
          pip install mypy
          mypy .

      - name: Run Tests 
        run: |
          pip install pytest 
          pytest 
